# Generated by Django 4.1 on 2022-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_category_alter_post_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('지원 정책', '지원 정책'), ('금융 상품', '금융 상품'), ('주간 소식', '주간 소식')], default='지원정책', max_length=20),
        ),
    ]
