# Generated by Django 4.1 on 2022-09-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="term",),
    ]
