# Generated by Django 4.1 on 2022-09-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_post_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="age1",
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="age2",
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
