# Generated by Django 4.1 on 2022-09-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_age1_post_age2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="age1",
            field=models.PositiveIntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="age2",
            field=models.PositiveIntegerField(blank=True, max_length=3, null=True),
        ),
    ]
