# Generated by Django 4.1 on 2022-09-12 15:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_rename_age2_post_max_age_rename_age1_post_min_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("지원 정책", "지원 정책"), ("금융 상품", "금융 상품"), ("주간 소식", "주간 소식")],
                default="지원 정책",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="income",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("무소득", "무소득"),
                    ("1~100만원", "1~100만원"),
                    ("101~200만원", "101~200만원"),
                    ("201~300만원", "201~300만원"),
                    ("301만원~400만원", "301만원~400만원"),
                    ("401만원초과", "401만원초과"),
                ],
                default="무소득",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="max_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="min_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="target",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("청년", "청년"),
                    ("미성년자", "미성년자"),
                    ("대학생", "대학생"),
                    ("직장인", "직장인"),
                    ("군인", "군인"),
                    ("기혼", "기혼"),
                    ("무주택자", "무주택자"),
                    ("장애인", "장애인"),
                    ("국가유공자", "국가유공자"),
                ],
                default="청년",
                max_length=60,
                null=True,
            ),
        ),
    ]
