# Generated by Django 4.1 on 2022-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_alter_post_category_alter_post_income_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="count",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
